version: '3'

services:
  miniflask:
    image: projectreclass/toynet-mininet:1174f9d091ed036f7b958e7e84c0bface8bf32cb

  mock_data_server:
    image: halverneus/static-file-server
    environment:
      - PORT=8888
    volumes:
      - ./toynet-content:/web

  backend:
    depends_on:
      - miniflask
    image: projectreclass/toynet-backend:1174f9d091ed036f7b958e7e84c0bface8bf32cb
    privileged: true
    ports:
      - "5000:5000"
    environment:
      - COMPOSE_NETWORK=toynet_mininet
      - TOYNET_IMAGE_TAG=projectreclass/toynet-mininet:1174f9d091ed036f7b958e7e84c0bface8bf32cb
      - FLASK_APP=flasksrc
      - MINI_FLASK_PORT=5000

    networks:
      - reclass_network
      - toynet_mininet
    volumes:
      - /lib/modules:/lib/modules
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - reclass_network
    depends_on:
      - backend
      - mock_data_server
    environment:
      - SERVER_URI="http://backend:5000"
      - CURR_URI="http://mock_data_server:8888"

networks:
  reclass_network:
  toynet_mininet:
    name: toynet_mininet
